import React from 'react'
import Index from '../../../Index'


export default function TermsAndCondition() {
      return (
            <>
                  <Index.Box className="admin-dashboard-content">
                        <Index.Box className="admin-user-list-flex admin-page-title-main">
                              <Index.Typography className='admin-page-title' component='h2' variant='h2'>Terms & Condition</Index.Typography>
                        </Index.Box>
                        <Index.Box className="cms-page-content-main privacy-policy-page common-card">
                              <Index.Box className="cms-page-content">
                                    <Index.Typography className="cms-page-content-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis luctus maximus pulvinar. Donec vel dolor et felis imperdiet pellentesque. Integer imperdiet leo ex, sit amet eleifend justo porttitor non. Praesent sapien turpis, blandit a mauris ut, vehicula vehicula nibh. Morbi faucibus quam ut risus tempor venenatis. Aenean eu tincidunt nibh, vel lacinia nisi. Suspendisse semper eros at vehicula facilisis. Sed eget justo in magna varius luctus. Vivamus et convallis magna, eu consectetur leo. Aliquam varius quam quam, a sodales dui bibendum at. Etiam tincidunt, mi a porttitor congue, nisl turpis commodo massa, a tempor purus velit nec libero. Aenean et lacinia ligula. In a neque ullamcorper, efficitur quam eget, scelerisque massa. Donec velit justo, suscipit eget bibendum quis, pharetra vitae dolor. Curabitur mollis egestas tellus nec rutrum.</Index.Typography>
                                    <Index.Typography className="cms-page-content-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis luctus maximus pulvinar. Donec vel dolor et felis imperdiet pellentesque. Integer imperdiet leo ex, sit amet eleifend justo porttitor non. Praesent sapien turpis, blandit a mauris ut, vehicula vehicula nibh. Morbi faucibus quam ut risus tempor venenatis. Aenean eu tincidunt nibh, vel lacinia nisi. Suspendisse semper eros at vehicula facilisis. Sed eget justo in magna varius luctus. Vivamus et convallis magna, eu consectetur leo. Aliquam varius quam quam, a sodales dui bibendum at. Etiam tincidunt, mi a porttitor congue, nisl turpis commodo massa, a tempor purus velit nec libero. Aenean et lacinia ligula. In a neque ullamcorper, efficitur quam eget, scelerisque massa. Donec velit justo, suscipit eget bibendum quis, pharetra vitae dolor. Curabitur mollis egestas tellus nec rutrum.</Index.Typography>
                                    <Index.Typography className="cms-page-content-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis luctus maximus pulvinar. Donec vel dolor et felis imperdiet pellentesque. Integer imperdiet leo ex, sit amet eleifend justo porttitor non. Praesent sapien turpis, blandit a mauris ut, vehicula vehicula nibh. Morbi faucibus quam ut risus tempor venenatis. Aenean eu tincidunt nibh, vel lacinia nisi. Suspendisse semper eros at vehicula facilisis. Sed eget justo in magna varius luctus. Vivamus et convallis magna, eu consectetur leo. Aliquam varius quam quam, a sodales dui bibendum at. Etiam tincidunt, mi a porttitor congue, nisl turpis commodo massa, a tempor purus velit nec libero. Aenean et lacinia ligula. In a neque ullamcorper, efficitur quam eget, scelerisque massa. Donec velit justo, suscipit eget bibendum quis, pharetra vitae dolor. Curabitur mollis egestas tellus nec rutrum.</Index.Typography>
                                    <Index.Typography className="cms-page-content-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis luctus maximus pulvinar. Donec vel dolor et felis imperdiet pellentesque. Integer imperdiet leo ex, sit amet eleifend justo porttitor non. Praesent sapien turpis, blandit a mauris ut, vehicula vehicula nibh. Morbi faucibus quam ut risus tempor venenatis. Aenean eu tincidunt nibh, vel lacinia nisi. Suspendisse semper eros at vehicula facilisis. Sed eget justo in magna varius luctus. Vivamus et convallis magna, eu consectetur leo. Aliquam varius quam quam, a sodales dui bibendum at. Etiam tincidunt, mi a porttitor congue, nisl turpis commodo massa, a tempor purus velit nec libero. Aenean et lacinia ligula. In a neque ullamcorper, efficitur quam eget, scelerisque massa. Donec velit justo, suscipit eget bibendum quis, pharetra vitae dolor. Curabitur mollis egestas tellus nec rutrum.</Index.Typography>
                                    <Index.Typography className="cms-page-content-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis luctus maximus pulvinar. Donec vel dolor et felis imperdiet pellentesque. Integer imperdiet leo ex, sit amet eleifend justo porttitor non. Praesent sapien turpis, blandit a mauris ut, vehicula vehicula nibh. Morbi faucibus quam ut risus tempor venenatis. Aenean eu tincidunt nibh, vel lacinia nisi. Suspendisse semper eros at vehicula facilisis. Sed eget justo in magna varius luctus. Vivamus et convallis magna, eu consectetur leo. Aliquam varius quam quam, a sodales dui bibendum at. Etiam tincidunt, mi a porttitor congue, nisl turpis commodo massa, a tempor purus velit nec libero. Aenean et lacinia ligula. In a neque ullamcorper, efficitur quam eget, scelerisque massa. Donec velit justo, suscipit eget bibendum quis, pharetra vitae dolor. Curabitur mollis egestas tellus nec rutrum.</Index.Typography>
                              </Index.Box>
                        </Index.Box>
                  </Index.Box>
            </>
      )
}
