const Api = {
  ADD_EDIT_USERS: "user/add-edit",
  LOGIN: "user/login",
  GET_USERS: "user/users",
  GET_PROFILE: "user/me",
  FORGOT_PASSWORD: "user/forgot-password",
  RESET_PASSWORD: "user/reset-password",
  EDIT_PROFILE: "user/edit-profile",
  GET_ADD_EDIT_ROLES: "user/roles",
  GET_ADD_EDIT_PERMISSIONS: "roles/permissions",
  GET_ADD_EDIT_ROLE: "user/roles",
  CHANGE_PASSWORD: "user/change-password",
  LOGOUT_USER: "user/logout",
  GET_ADD_EDIT_SITE: "site/sites",
  CHIRPSTACK: "chirpstack/chirpstack",
  GET_ADD_EDIT_GATEWAYS: "gateway/gateways",
  GET_ADD_EDIT_BLOCKS: "block/blocks",
  GET_ADD_EDIT_DEVICES: "device/devices",
  GET_OVERVIEW_DATA: "overview/overview",
  GET_DASHBOARD_DATA: "dashboard",
  GET_ROWS: "row/rows",
  GET_REPORTS: "report",
  GET_CHIRP_STACK_DEVICE: "devices",
  SEND_COMMANDS: "devices",
  GET_MQTT_DATA: "telemetry",
  GET_HISTORICAL_DATA: "historical",
  // ROBOT_IMPORT_DATA: "chirpStack/multi-robot-import",
  // CHECK_ROBOT_IMPORT_DATA: "chirpStack/import-counter/latest",
  MULTICAST_GROUPS: "multicast-groups",
  UNICAST_FUOTA: "chirpStack/fouta",
  MULTICAST_FUOTA: "chirpStack/multicast-fouta",
};
export { Api };
